<h1>Articles</h1>
<a href="http://localhost/zblog.local/public/index.php/admin/article/add/">Add article</a><br><br>
<?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s><button type = "button" class = "close"'
            . ' data-dismiss = "alert" aria-hidden = "true"> &times; </button>'
            . ' <ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>

<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>#</th>
            <th>Category</th>
            <th>Title</th>
            <th>Article</th>
            <th>Beginning of the article</th>
            <th>Publication</th>
            <th>Act</th>
        </tr>
        <?php
        foreach ($articles as $item){
            $category = $item->getCategory();
            if($category){
                $catName = $category->getCategoryName();
            } else {
                $catName = '';
            }
            if($item->getIsPublic()){
                $isPublic = 'Yes';
            } else {
                $isPublic = 'No';
            }
            
            echo " <tr>"
            . "<td>{$item->getId()}</td>"
            . "<td>{$catName}</td>"
            . "<td>{$item->getTitle()}</td>"
            . "<td>{$item->getArticleForTable()}</td>"
            . "<td>{$item->getShortArticleForTable()}</td>"
            . "<td>{$isPublic}</td>";
            
            echo '<td><a href="' . $this->url('admin/article', array('action' => 'edit', 'id' => $item->getId())).'"> Edit </a>&nbsp;&nbsp;
                      <a href="' . $this->url('admin/article', array('action' => 'delete', 'id' => $item->getId())).'" onclick="if (confirm(\'Delete title?\')){document.location = this.href;} return false;"> Delete </a></td>';
        }
        ?>
    </tbody>
</table>

<?php
    echo $this->paginationControl($articles, 'Sliding', 'pagination_control',
            array('route' => 'admin/article'));
?>
