<hr/>
<table class="table">
    <tr>
        <th>User's name</th>
        <th>Password</th>
        <th>Email</th>
    </tr>
    <?php foreach ($users as $user) { ?>
    <tr>
        <td><?php echo $this->escapeHtml($user->getUsrName()); ?></td>
        <td><?php echo $this->escapeHtml($user->getUsrPassword()); ?></td>
        <td><?php echo $this->escapeHtml($user->getUsrEmail()); ?></td>
    </tr>
    <?php } ?>
</table>
