<h1>Category</h1>
<a href="http://localhost/zblog.local/public/index.php/admin/category/add/">Add</a><br><br>
<?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>');
    
echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));

?>

<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>#</th>
            <th>Key</th>
            <th>Name</th>
            <th>Act</th>
        </tr>
        <?php
            foreach ($category as $item){
                echo "<tr><td>{$item->getId()}</td><td>{$item->getCategoryKey()}</td><td>{$item->getCategoryName()}</td>";
                echo '<td><a href="' . $this->url('admin/category', array('action' => 'edit', 'id' => $item->getId())).'"> Edit </a>&nbsp;&nbsp;
                          <a href="' . $this->url('admin/category', array('action' => 'delete', 'id' => $item->getId())).'" onclick="if (confirm(\'Delete title?\')){document.location = this.href;} return false;"> Delete </a></td>';
                
            }
        ?>
    </tbody>
</table>
