<?php

echo "<article>"
. "<div class = 'page-header'>"
    . "<h3 style = 'front-size: 2em; text-align: center'>{$article->getTitle()}</h3>"
. "</div>"
."<div class='container'>
<div class='row'>
    <div class='col-lg-6 col-md-6 col-sm-6 col-xs-9'><img style='max-height: 500px; padding-bottom: 50px' src='..\..\img\\{$article->getBookImg()}.jpg'></div>
    <div class='col-lg-6 col-md-6 col-sm-6 col-xs-12'>
        <div style='margin-bottom: 25px; margin-top: 25px'><span style='font-size: 24px; color: green;'>{$article->getPrice()} грн</span></div>
        <div>{$article->getFullArticle()}</div>

<button class='btn btn-primary cart' id='{$article->getId()}' onclick='return buy({$article->getId()})'>Купити</button>
    </div>   
</div>
</div>"

    . "</article>"

?>

<div class="bs-docs-section">
    <div class="well">
        <?php
            $form->setAttribute('action', $this->url('blog', array('action' => 'comment-add')));
            $form->setAttribute('class', 'form-horizontal');
            $form->prepare();
            echo $this->form()->openTag($form);
            echo '<fieldset><legend>Add comment</legend>';
            echo '<div id="comment_errors"></div>';
            
            $e = $form->get('userEmail');
            $e->setLabelAttributes(array('class' => 'col-lg-2 control-label'));
            echo '<div class = "form-group">';
            echo $this->formLabel($e);
            echo "<div class = 'col-lg-10'>{$this->formEmail($e)}</div>";
            echo '</div>';
            
            $e = $form->get('comment');
            $e->setLabelAttributes(array('class' => 'col-lg-2 control-label'));
            echo '<div class = "form-group">';
            echo $this->formLabel($e);
            echo "<div class = 'col-lg-10'>{$this->formTextarea($e)}</div>";
            echo '</div>';
            
            echo "<input type='hidden' value='{$article->getId()}' name='article'>";
            
            echo $this->formRow($form->get('submit'));
            echo '</fieldset>';
            echo $this->form()->closeTag();
        ?>
    </div>
</div>

<script>
    $(function(){
       $("form#comment").submit(function(){
           var fData = $('#comment').serialize();
           $.ajax({
               url: '/zblog.local/public/comment-add/',
               type: 'post',
               dataType: 'json',
               data: fData,
               success: function(data){
                   if(data['success'] == 1){
                       $('#new-comment-email h3').html($('#user_email').val());
                       $('#new-comment-body').html($('#user_comment').val());
                       $('#new-comment').show();
                       
                       $('.bs-docs-section').hide('slow');
                       $('#no-comments').hide();
                   } else {
                       $('#comment_errors').html('');
                       for(var key in data){
                           $('#comment_errors').append('<span>'+data[key]+'</span>');
                       }
                   }
               }
           });
           return false;
       }); 
    });
</script>

<?php
$comments = $article->getComments();

$commentCnt = $comments->count();
if($commentCnt){
    echo "<h3>Comments ({$commentCnt})</h3>";
    foreach ($comments as $comment){
        echo "<div class = 'panel panel-default'>"
        . "<div class = 'panel-heading'>{$comment->getUserEmail()}</div>"
        . "<div class = 'panel-body'>{$comment->getComment()}</div>"
            . "</div>";
    }
} else {
    echo "<h3 id = 'no-comments'>No comments</h3>";
}
?>


<div id='new-comment' class="panel panel-success" style="display: none;">
    <div id='new-comment-email' class="panel-heading"><h3 class="panel-title"></h3></div>
    <div id='new-comment-body' class="panel-body"></div>
</div>

<!--<script>-->
<!--    function buy(id) {-->
<!--        $.ajax({-->
<!--            url: '/zblog.local/public/cart/',-->
<!--            type: 'post',-->
<!--            dataType: 'json',-->
<!--            data: id,-->
<!--        success: function(result){-->
<!--            alert(result);-->
<!--            console.log(result);-->
<!--        }-->
<!--        });-->
<!--        alert(id);-->
<!--    }-->
<!--</script>-->


<!--<script>-->
<!--    $(function(){-->
<!--        $(".cart").submit(function(){-->
<!--            var fBook = $('.cart').serialize();-->
<!--            $.ajax({-->
<!--                url: '/zblog.local/public/cart/',-->
<!--                type: 'post',-->
<!--                dataType: 'json',-->
<!--                data: fBook,-->
<!--                success: function(data){-->
<!--                    if(data['success'] == 1){-->
<!--                        console.log("hello");-->
<!--                    }-->
<!--                }-->
<!--            });-->
<!--            return false;-->
<!--        });-->
<!--    });-->
<!--</script>-->

