<h1>Comments</h1>

<?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s><button type = "button" class = "close"'
            . ' data-dismiss = "alert" aria-hidden = "true"> &times; </button>'
            . ' <ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>

<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>#</th>
            <th>Article</th>
            <th>Email</th>
            <th>Comment</th>
            <th>Act</th>
        </tr>
        <?php
        foreach ($comments as $item){
            echo " <tr>"
            . "<td>{$item->getId()}</td>"
            . "<td>{$item->getArticle()->getTitle()}</td>"
            . "<td>{$item->getUserEmail()}</td>"
            . "<td>{$item->getComment()}</td>";
            
            //If you want to edit the comments
            //<a href="' . $this->url('admin/comment', array('action' => 'edit', 'id' => $item->getId())).'"> Edit </a>&nbsp;&nbsp;
            
            echo '<td><a href="' . $this->url('admin/comment', array('action' => 'delete', 'id' => $item->getId())).'" onclick="if (confirm(\'Delete comment?\')){document.location = this.href;} return false;"> Delete </a></td>';
        }
        ?>
    </tbody>
</table>

<?php
    echo $this->paginationControl($comments, 'Sliding', 'pagination_control',
            array('route' => 'admin/comment'));
?>

